name: CI

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm i
      - name: Verify linter
        run: npm run lint:check
      - name: Build app      
        run: npm run build --if-present